server:
  port: 1234  # Cổng chạy ứng dụng
#  servlet:
#    context-path: /${spring.application.name}/api  # Định nghĩa context path (URL gốc của API)

spring:
  application:
    name: san_tiktok  # Tên ứng dụng
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
    username: san_tiktok
    password: Xiang@96
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: validate
    #     validate: Hibernate sẽ kiểm tra entity với bảng có sẵn- Không tạo bảng mới nếu chưa có-Không update schema tự động-Nếu entity mới không có trong DB, nó sẽ báo lỗi startup.
    show-sql: true      # Hiển thị câu lệnh SQL trong console
    database-platform: org.hibernate.dialect.Oracle12cDialect
    properties:
      hibernate:
        default_schema: ${spring.application.name}
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#    #      registryFetchIntervalSeconds: 30  # Khoảng thời gian giữa các lần fetch danh sách dịch vụ từ Eureka Server
#    #      renewThreshold: 300000  # Thời gian tối đa giữa các lần gia hạn đăng ký dịch vụ (mặc định là 30 phút)
#    #      initialInstanceInfoReplicationIntervalSeconds: 5  # Thời gian để Eureka Client gửi thông tin đến Server
#    registerWithEureka: true  # Client đăng ký dịch vụ với Eureka
#    fetchRegistry: true  # Client lấy thông tin từ Eureka Server


  jackson:
    serialization:
      indent-output: true  # Format JSON đẹp hơn
    default-property-inclusion: non_null  # Ẩn các giá trị null

logging:
  level:
    root: DEBUG
    org.springframework: DEBUG
    sansan.tool: DEBUG
